################################
# ExperienceJails v${project.version}
# Insider Build for MinecraftExperience Network | Kingdoms
#
# By tommaso.benatti#0001 : Sodio#2005
#
# Config updated at the version: 0.1
#
# All rights reserved | 2021 MinecraftExperience™
################################

#################################################
#   ______                      _                          _       _ _
#  |  ____|                    (_)                        | |     (_) |
#  | |__  __  ___ __   ___ _ __ _  ___ _ __   ___ ___     | | __ _ _| |___
#  |  __| \ \/ / '_ \ / _ \ '__| |/ _ \ '_ \ / __/ _ \_   | |/ _` | | / __|
#  | |____ >  <| |_) |  __/ |  | |  __/ | | | (_|  __/ |__| | (_| | | \__ \
#  |______/_/\_\ .__/ \___|_|  |_|\___|_| |_|\___\___|\____/ \__,_|_|_|___/
#              | |
#              |_|
#
################################

# >>> Permissions <<<
#
# experiencejails.help
# experiencejails.create
#
################################

# >>> Database <<<
  # Models
    # Jailed player example
      # Nickname | join date | leave date | jail name | reason | staffer
    # Created jails example
      # jail name | x | y | z | world
# Database Credentials
ADDRESS: "localhost"
USERNAME: "root"
PASSWORD: "root"
DATABASE: "exp_jails"
PORT: "3306"
#
#
################################

################################
# >>> Messages <<<

defaultMessages:
  denied: "&cYou have no permission to do that!"
  onlyPlayer: "&cOnly player!"
  pluginException: "&cPlugin has thrown a Exception, contact Server Administrator!"
  noJail: "&cThere's no jail with that name!"
  noArgs: "&cNo arguments valid."
  jailCreated: "&dJail {0} created successfully."
  exceptionError: "&cThere was a exception, please retry later."
  configReloaded: "&cConfig Reloaded."
  alreadyCreated: "&cJail was already created!\nCheck jail lists."
  jailDeleted: "&cJail {0} has been deleted"