################################
# ExperienceJails v${project.version}
# Insider Build for MinecraftExperience Network | Kingdoms
#
# By tommaso.benatti#0001 : Sodio#2005
#
# Config updated at the version: 0.1
#
# All rights reserved | 2021 MinecraftExperience™
################################

#################################################
#   ______                      _                          _       _ _
#  |  ____|                    (_)                        | |     (_) |
#  | |__  __  ___ __   ___ _ __ _  ___ _ __   ___ ___     | | __ _ _| |___
#  |  __| \ \/ / '_ \ / _ \ '__| |/ _ \ '_ \ / __/ _ \_   | |/ _` | | / __|
#  | |____ >  <| |_) |  __/ |  | |  __/ | | | (_|  __/ |__| | (_| | | \__ \
#  |______/_/\_\ .__/ \___|_|  |_|\___|_| |_|\___\___|\____/ \__,_|_|_|___/
#              | |
#              |_|
#
################################

# >>> Permissions <<<
#
# experiencejails.help
#
################################
