name: ExperienceJails
version: '${project.version}'
main: it.minecraftexperience.experiencejails.Main
api-version: 1.17
authors: [ tommasobenatti, IllegalNatrium ]
description: A simple plugin for Jails, made for Kingdoms
website: www.mcexp.it

permissions:
  experiencejails.jail:
    description: "Useful for jailing players"
  experiencejails.create:
    description: "Useful for creating jails"
  experiencejails.teleport:
    description: "Useful for teleporting to jails"

commands:
  jcore:
    description: "Core Command"