name: ExperienceJails
version: '${project.version}'
main: it.minecraftexperience.experiencejails.Main
api-version: 1.17
authors: [ tommasobenatti, IllegalNatrium ]
description: A simple plugin for Jails, made for Kingdoms
website: www.mcexp.it

commands:
  jcore:
    description: ".."